### ISSUE TITLE
Hackathon task list

### ISSUE THREAD

**Issue by vincenzocoia** [probaverse/couple#1]
Take your pick! Most of them should be ready to go without any prerequisites. Indicate here what you want to work on. And please all take a stab at Task 1 🙂 . And feel free to ping me on Teams, I'll probably be able to get back to you pretty quickly.

**My task**: I'll be trying to (1) bring in the IG and IGL copulas from my igcop package, and making functions to turn those into copula objects; and (2) bringing in the _source code_ for the [Frank ("frk") copula from the CopulaModel package](https://github.com/vincenzocoia/CopulaModel/blob/9fac5106f374bdea6df82dc8601c66562b06bd67/R/copcdfpdf.R); (3) bringing in the tests for the Frank copula.

### Before you start...

Here are some resources where you can learn more about various things:

- How to make an R package:
     - video (featuring me 🙂): https://www.youtube.com/watch?v=SGh_t7zlC7U
     - "The Whole Game" book chapter: https://r-pkgs.org/whole-game.html 
- The distionary R package can be found at https://github.com/vincenzocoia/distionary -- we will be mimicking that, but for copulas. There is also distplyr (at https://github.com/vincenzocoia/distplyr), which manipulates distributions, and it would be useful to have such a thing for copulas, too.
- Testing functions with the testthat R package:
    - 13.4.2 in the R Packages book: https://r-pkgs.org/testing-basics.html#create-a-test 
    - Video (start at 7:26): https://youtu.be/3nDgR7l5Tps?t=446 
        - The whole video might be useful if making functions is new to you.

## Warmup

1.	Everyone: if you can, try adopting the “github flow” (https://docs.github.com/en/get-started/quickstart/github-flow#following-github-flow) by working on a branch. This way, when you add code to the package that you think is ready to be integrated, you can submit a pull request so that your code can be reviewed. If this is too difficult, no problem, we’ll make it work.
2.	Make a test function. Document it, then run `document()` and reinstall the package. After restarting RStudio, can you load the package, view your function’s documentation, and use the function?
3.	Write a simple test for your function using the testthat package. When you’re done writing the test, click “Check” in RStudio, or execute the `check()` function from devtools. Were any new errors induced? Did you use the `use_test()` function to make your test file?

## Beginnings: independence copula

4.	Make a function `dindep` that takes vectors `u` and `v` as its input, and returns the density of the independence copula, which is simply 1 everywhere on the unit square, and 0 elsewhere. Bonuses: (1) Can you use the `vctrs::vec_recycle_common()` function to ensure that `u` and `v` are the same length? Either their lengths should match, or one of them is allowed to be length 1. (2) Can you implement NA handling, where NA is returned whenever an entry of `u` or `v` is NA? (3) Does the function still work if one or both of `u` and `v` have zero length – that is, inputting `numeric(0)` as either `u` or `v` (the output should be `numeric(0)`. (4) Can you record these checks as official tests?
5.	Make a function `pindep` that takes vectors `u` and `v` as its input, and returns the cdf of the independence copula, which is simply u*v everywhere on the unit square, =1 when both u and v > 1, =0 when either u or v is negative, =u when v>1, and =v when u>1. Bonuses: (1) Can you use the `vctrs::vec_recycle_common()` function to ensure that `u` and `v` are the same length? Either their lengths should match, or one of them is allowed to be length 1. (2) Can you implement NA handling, where NA is returned whenever an entry of `u` or `v` is NA? (3) Does the function still work if one or both of `u` and `v` have zero length – that is, inputting `numeric(0)` as either `u` or `v` (the output should be `numeric(0)`. (4) Can you record these checks as official tests?
6.	Make a function `realise.indep(copula, n)`, that returns an nx2 data frame of entirely random numbers between 0 and 1 (you can use `runif()` from the stats package). Name the columns “.u” and “.v”. To use the function once complete, the “realise” generic (Task 10) and independence copula object (Task 7) will need to be complete first, after which you should just be able to call `realise()` on an independence copula (no need for calling `realise.indep()`. Bonuses: (1) if the user has the `tibble` package installed on their computer, can you convert the data frame to a tibble? Hint, see my `rigl()` function, which outputs a similar thing https://github.com/vincenzocoia/igcop/blob/main/R/igl.R#L104 (2) Does your function output a data frame with 0 rows if `n = numeric(0)` is input? (3) Can you write a formal unit test containing that check?
7.	Make the “independence copula” object by making the function `cop_indep()`. Use the `cop_parametric()` function already in the package, similar to how `dst_norm()` creates a Normal distribution in the distionary package (https://github.com/vincenzocoia/distionary/blob/main/R/dst_norm.R), except keep in mind that the Normal distribution has two parameters (mean and variance), whereas the independence copula has no parameters, so the `cop_indep()` function you’ll be making will have no arguments, and there is thus no need to check that the input is valid. Note: make sure you use `.env = "package:distionary"` as an argument when calling the `dst_parametric()` function here. Bonus: can you write a formal unit test that checks that this object is of class “indep” (i.e., “indep” should be first in the list when calling the `class()` function on an independence copula), and that it also has the class “cop”?

## Beginnings: generics

- [x] Make a generic function for evaluating the cdf of a copula. The R script should look almost identical to https://github.com/vincenzocoia/distionary/blob/main/R/eval_cdf.R. – although feel free to leave out the “enframe” function, unless you’re feeling adventurous (I suggest checkout out what it does in the distionary/distplyr universe). Bonus: also make a generic for the survival function, which should almost be identical to https://github.com/vincenzocoia/distionary/blob/main/R/eval_survival.R. 
- [x] Make a generic function for evaluating the density of a copula. The R script should look almost identical to https://github.com/vincenzocoia/distionary/blob/main/R/eval_cdf.R. – although feel free to leave out the “enframe” function, unless you’re feeling adventurous (I suggest checkout out what it does in the distionary/distplyr universe).
- [x] Make a generic function `realise()` (and alias `realize()`) for randomly generating data from a copula. The R script should look almost identical to https://github.com/vincenzocoia/distionary/blob/main/R/realise.R
